use cookie_store::CookieStore as InternalCookieStore;
use reqwest::cookie::CookieStore;
use reqwest::header::HeaderValue;
use std::sync::RwLock;

pub struct ZingCookieStore(pub RwLock<InternalCookieStore>);

impl ZingCookieStore {
    pub fn new() -> Self {
        Self(RwLock::new(InternalCookieStore::new()))
    }

    pub fn from_netscape_file<P: AsRef<std::path::Path>>(path: P) -> Result<Self, String> {
        let content = std::fs::read_to_string(path).map_err(|e| format!("{e}"))?;
        let store = Self::new();
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') || line.starts_with("HTTP") {
                continue;
            }
            let parts: Vec<&str> = line.split('\t').collect();
            if parts.len() < 7 {
                continue;
            }
            let domain = parts[0].trim_start_matches('.');
            let cookie_path = parts[2];
            let secure = parts[3] == "TRUE";
            let name = parts[5];
            let value = parts[6];
            let scheme = if secure { "https" } else { "http" };
            let url_str = format!("{scheme}://{domain}{cookie_path}");
            let cookie_str = format!(
                "{name}={value}; Domain={domain}; Path={cookie_path}{}",
                if secure { "; Secure" } else { "" }
            );
            if let Ok(url) = url::Url::parse(&url_str) {
                if let Ok(c) = cookie::Cookie::parse(cookie_str) {
                    let _ = store
                        .0
                        .write()
                        .map_err(|e| format!("{e}"))
                        .map(|mut s| {
                            s.store_response_cookies(
                                std::iter::once(c.into_owned()),
                                &url,
                            );
                        });
                }
            }
        }
        Ok(store)
    }

    pub fn save_netscape<P: AsRef<std::path::Path>>(&self, path: P) -> Result<(), String> {
        let store = self.0.read().map_err(|e| format!("{e}"))?;
        let mut file =
            std::fs::File::create(path).map_err(|e| format!("Cannot create cookie file: {e}"))?;
        use std::io::Write;
        writeln!(file, "# Netscape HTTP Cookie File").map_err(|e| format!("{e}"))?;
        writeln!(file, "# Generated by zing").map_err(|e| format!("{e}"))?;
        for cookie in store.iter_unexpired() {
            let domain = cookie.domain().unwrap_or("");
            let flag = if domain.starts_with('.') { "TRUE" } else { "FALSE" };
            let path = cookie.path().unwrap_or("/");
            let secure = if cookie.secure().unwrap_or(false) {
                "TRUE"
            } else {
                "FALSE"
            };
            let expires = cookie
                .expires()
                .map(|e| match e {
                    cookie::Expiration::DateTime(dt) => dt.unix_timestamp(),
                    cookie::Expiration::Session => 0,
                })
                .unwrap_or(0);
            writeln!(
                file,
                "{}\t{}\t{}\t{}\t{}\t{}\t{}",
                domain,
                flag,
                path,
                secure,
                expires,
                cookie.name(),
                cookie.value()
            )
            .map_err(|e| format!("{e}"))?;
        }
        Ok(())
    }
}

impl CookieStore for ZingCookieStore {
    fn set_cookies(
        &self,
        cookie_headers: &mut dyn Iterator<Item = &HeaderValue>,
        url: &url::Url,
    ) {
        let iter = cookie_headers.filter_map(|val| {
            std::str::from_utf8(val.as_bytes())
                .ok()
                .and_then(|s| cookie::Cookie::parse(s).ok())
                .map(|c| c.into_owned())
        });
        if let Ok(mut store) = self.0.write() {
            store.store_response_cookies(iter, url);
        }
    }

    fn cookies(&self, url: &url::Url) -> Option<HeaderValue> {
        let store = self.0.read().ok()?;
        let s: Vec<String> = store
            .get_request_values(url)
            .map(|(name, value)| format!("{name}={value}"))
            .collect();
        if s.is_empty() {
            None
        } else {
            HeaderValue::from_str(&s.join("; ")).ok()
        }
    }
}

impl Default for ZingCookieStore {
    fn default() -> Self {
        Self::new()
    }
}
