[package]
name = "zing-ext"
version = "0.1.6"
edition = "2021"
description = "Extensions for the zing downloader"
authors = ["Tharuk Renuja"]
license = "GPL-3.0-only"

[dependencies]
url = "2"
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "fs"] }
sha2 = "0.10"
sha-1 = "0.10"
md-5 = "0.10"
quick-xml = "0.36"

[dev-dependencies]
tempfile = "3"